version: "3.8"

services:
  web:
    image: mehulsacr.azurecr.io/generic:latest
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload

    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    image: mehulsacr.azurecr.io/generic:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7

  nginx:
    image: mehulsacr.azurecr.io/nginx:latest
    ports:
      - 80:80
    environment:
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=true
    depends_on:
      - web
      - dashboard

  dashboard:
    image: mehulsacr.azurecr.io/generic:latest
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --broker_api=/api/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
