name: Docker Image CI

on:
  push:
    branches: ["master"]
#   pull_request:
#     branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: mehulsacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build ./project -t mehulsacr.azurecr.io/generic:latest
          docker push mehulsacr.azurecr.io/generic:latest
      - name: "Trigger Webhook"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -d '' "${WEBHOOK_URL}"
